#!/bin/sh

uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase=/luci-static/argon
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

#set newtwork	
uci set network.lan.ipaddr="192.168.100.1"
uci set network.wan.proto=dhcp
uci set network.wan.ifname=eth5
uci set network.wan6.ifname=eth5
uci commit network

if [ ! -f /etc/config/placeholder ]; then

  uci set mwan3.wan.enabled='0'
  uci commit mwan3
  
  uci del dockerman.local.daemon_ea
  uci commit dockerman
  
  uci set firewall.@defaults[0].fullcone='1'
  uci commit firewall
  
  uci set flowoffload.@flow[0].bbr='1'
  uci commit flowoffload
  
  uci set shadowsocksr.@global[0].pdnsd_enable='0'
  uci del shadowsocksr.@global[0].tunnel_forward
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='1.1.1.1'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='208.67.222.222'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.8.8'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='8.8.4.4'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='9.9.9.9'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='218.102.23.228'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='210.0.255.250'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='168.95.1.1'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='202.175.82.46'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='77.88.8.8'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='101.101.101.101'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='203.198.7.66'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='202.56.128.30'
  uci add_list shadowsocksr.@access_control[0].wan_fw_ips='149.112.112.112'
  uci commit shadowsocksr
  
  uci set smartdns.@smartdns[0].enabled='1'
  uci set smartdns.@smartdns[0].seconddns_enabled='0'
  uci set smartdns.@smartdns[0].redirect='none'
  uci set smartdns.@smartdns[0].tcp_server='1'
  uci set smartdns.@smartdns[0].prefetch_domain='1'
  uci set smartdns.@smartdns[0].serve_expired='1'
  uci commit smartdns

[ -f "/etc/config/smartdns" ] && {
cat >> /etc/config/smartdns <<EOF
config server
	option name 'DNSPod'
	option type 'https'
	option ip 'https://doh.pub/dns-query'
	option addition_arg ' -check-edns'
	option enabled '1'
	option blacklist_ip '0'
	option no_check_certificate '0'
config server
	option name 'AliDNS'
	option type 'https'
	option ip 'https://dns.alidns.com/dns-query'
	option addition_arg ' -check-edns'
	option enabled '1'
	option blacklist_ip '0'
	option no_check_certificate '0'
config server
	option name '114'
	option type 'tcp'
	option ip '114.114.114.114'
	option blacklist_ip '1'
	option addition_arg ' -check-edns'
	option enabled '1'
config server
	option name 'Cloudflare'
	option type 'https'
	option server_group 'oversea'
	option blacklist_ip '0'
	option no_check_certificate '0'
	option enabled '1'
	option ip 'https://1.1.1.1/dns-query'
	option addition_arg '-host-name cloudflare-dns.com -check-edns'
config server
	option name 'Google'
	option type 'https'
	option blacklist_ip '0'
	option no_check_certificate '0'
	option ip 'https://8.8.8.8/dns-query'
	option addition_arg '-host-name dns.google -check-edns'
	option enabled '1'
config server
	option name 'Quad9'
	option type 'https'
	option blacklist_ip '0'
	option no_check_certificate '0'
	option ip 'https://9.9.9.11/dns-query'
	option addition_arg '-host-name dns11.quad9.net -check-edns'
	option enabled '1'
EOF
}
fi

#The default password is "password"
#sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i "s/# //g" /etc/opkg/distfeeds.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

# Enable ssh RootLogin
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
service sshd restart

touch /etc/config/placeholder

exit 0
