#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
# 删除历史编译，手动触发的11111
#=================================================


name: Delete Releases
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/deleteReleases.yml'
      
env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  x86:
    runs-on: ubuntu-latest
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Delete
      uses: goofysun/action-delete-allrelease@master
      with:
        github_token: ${{ secrets.REPO_TOKEN }}
